- name: clean yum
  shell: "if test -f /usr/bin/yum; then yum clean all || exit 2; echo CLEANED; fi; true"
  become: yes
  register: done
  changed_when: "'CLEANED' in done.stdout"
- name: clean zypper
  shell: "if test -f /usr/bin/zypper; then zypper clean || exit 2; echo CLEANED; fi; true"
  become: yes
  register: done
  changed_when: "'CLEANED' in done.stdout"
