- hosts: localhost
  vars:
     base_image: "centos:7.9.2009"
     base_command: "sleep 900"
     tagrepo: "localhost:5000/systemctl"
     tagname: "elasticsearch"
     tagversion: "latest"
     docker: docker
  tasks:
    - name: downloads upfront
      import_role:
         name: "elasticsearch"
         tasks_from: "software_download.yml"
         allow_duplicates: yes
    - name: name of setup container
      set_fact:
         container1: "{{ tagname.replace('/','-') + '-build-' + lookup('pipe', 'echo $PPID') }}"
    - name: name of setup container
      set_fact:
         container1: "{{ tagname.replace('/','-') + '-build-' }}"
      when: LOCAL is defined
    - debug: var=setup_container
    - name: remove setup container
      command: "{{docker}} rm -f '{{ container1 }}'"
      ignore_errors: yes
    - name: start docker mirror package repo
      shell: ./docker_mirror.py start {{base_image}} -a
      register: mirror
    - name: start setup container
      command: "{{docker}} run -d --rm=true {{ mirror.stdout_lines[0] }} \
                       --name '{{ container1 }}' '{{ base_image }}' {{base_command}}"
    - name: initial setup container
      add_host:
        hostname: "{{ container1 }}"
        ansible_connection: 'docker'
        ansible_user: "root"
        # ansible_python_interpreter: /usr/bin/python
    - name: setup ansible user
      delegate_to: "{{ container1 }}"
      import_role: 
         name: "setup-ansible-user"
      vars:
         setup_ansible_docker: yes
    - name: setup systemctl replacement
      delegate_to: "{{ container1 }}"
      import_role:
        name: "setup-systemctl-replacement"
      vars:
        setup_ansible_docker: yes
    - name: attach setup container
      add_host:
        hostname: "{{ container1 }}"
        groups: redis
        ansible_connection: 'docker'
        ansible_user: "{{ setup_ansible_user }}"
        #             ^^^^^^^^^
        # ansible_python_interpreter: /usr/bin/python

- name: setup elasticsearch
  import_playbook: "centos7-elasticsearch.yml"

- hosts: localhost
  vars:
     tagrepo: "localhost:5000/systemctl"
     tagname: "elasticsearch"
     tagversion: "latest"
     docker: docker
  tasks:
    - name: commit the container
      command: "{{docker}} commit \
        -c 'CMD [\"/usr/bin/systemctl\"]' \
        '{{ container1 }}' '{{ tagrepo }}/{{ tagname }}:{{ tagversion }}'"
    - name: remove setup container
      command: "{{docker}} rm -f '{{ container1 }}'"
      ignore_errors: yes
