- name: qtest_service
  set_fact:
     qtest_service: "qtest.service"
  when: qtest_service is undefined
- name: start qtest
  service:
     name: "{{qtest_service}}"
     state: started
  become: yes
  register: done
  # failed_when: "'successfully stopped' not in done.stdout"
- name: wait for logfile
  shell: |
    for i in 1 2 3 4 5 6 7 8 9; do
        sleep 1
        logfile=`find {{qtest_home}}/logs -type f`
        if test -f "$logfile"; then
            echo "$logfile"
            break
        fi
    done
  register: logfile_found
- name: set logfile_found
  set_fact:
     qtest_logfile: "{{ logfile_found.stdout_lines | last }}"
- debug: var=qtest_logfile
- name: wait start complete
  wait_for:
    path: "{{qtest_logfile}}"
    search_regex: "qtestctl stop"
    timeout: 500
  # actually about 150-200 seconds (ansible has 300 seconds default)
- name: stop qtest
  service:
     name: "{{qtest_service}}"
     state: stopped
  become: yes
  register: done
