# Copyright (C) 2017 Guido U. Draheim, All Rights Reserved

- name: install software
  shell: |
    yum install -y which # TODO: missing dependency of elasticsearch
    yum install -y {{elasticsearch_software}}/{{elasticsearch_rpm}}
  become: yes
- name: enable software
  service:
    name: "{{elasticsearch_service}}"
    enabled: yes
  become: yes
- name: check version
  shell: "rpm -q --info elasticsearch | grep Version"
  register: installedversion
- debug: var=installedversion.stdout
- name: allow any
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    insertafter: "#network.host"
    regexp: "^network.host:.*"
    line: "network.host: 0.0.0.0"
  become: yes
- name: truncate systemctl.py
  shell: truncate -s0 -c /var/log/systemctl.log
  become: yes
