- name: install java
  package: pkg="{{item}}" state="installed"
  become: yes
  with_items: "{{elasticsearch_java_packages}}"
- name: reinstall systemctl.py
  shell: "test ! -f /usr/bin/systemctl.py || cp -v /usr/bin/systemctl.py /usr/bin/systemctl"
  register: done
  changed_when: "' -> ' in done.stdout"
