# Copyright (C) 2017 Guido U. Draheim, All Rights Reserved

- set_fact:
    elasticsearch_rpm: "{{ elasticsearch_download | basename }}"
  when: elasticsearch_rpm is undefined
- name: upload check
  local_action: 'stat path="{{elasticsearch_software}}/{{elasticsearch_rpm}}"'
  register: have_download
- name: inst dir
  file: 
    path: "{{elasticsearch_software}}" 
    state: "directory" 
    owner: "{{ansible_user}}"
  become: yes
- name: upload rpm
  copy: 
    src: "{{elasticsearch_software}}/{{elasticsearch_rpm}}" 
    dest: "{{elasticsearch_software}}"
  when: have_download.stat.exists
