# Copyright (C) 2023 Guido U. Draheim, All Rights Reserved

- name: current user - workaround Ansible 2.9
  shell: id -un
  become: false
  register: current_whoami
  when: ansible_user is not defined
- name: current_user - workaround Ansible 2.9
  set_fact:
     current_user: "{{current_whoami.stdout}}"
  when: ansible_user is not defined
- name: current_user - ansible_user
  set_fact:
     current_user: "{{ansible_user}}"
  when: ansible_user is defined
- name: download check
  stat: path="{{elasticsearch_software}}/{{elasticsearch_rpm}}"
  register: need_download
- name: "mkdir for software"
  file:
    path: "{{elasticsearch_software}}"
    owner: "{{current_user}}"
    state: "directory"
- name: download the software
  get_url:
    dest: "{{elasticsearch_software}}"
    url: "{{elasticsearch_download}}/{{elasticsearch_rpm}}"
  when: not need_download.stat.exists
