# the actual setup has went into a separate ansible role - please check:
# : roles/setup-systemctl-replacement/tasks/systemctl-docker-replacement.yml
- name: reinstall systemctl.py
  shell: "test ! -f /usr/bin/systemctl.py || cp -v /usr/bin/systemctl.py /usr/bin/systemctl"
  become: yes
  register: done
  changed_when: "' -> ' in done.stdout"
